# Generated by Django 3.2.24 on 2024-03-02 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_ingredients"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.CreateModel(
            name="Sku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.PositiveSmallIntegerField(help_text="Size of SKU in grams"),
                ),
                (
                    "price",
                    models.PositiveSmallIntegerField(
                        help_text="Price payable by customer (Rs.)",
                        verbose_name="Selling price (Rs.)",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sku",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
