# Generated by Django 3.2.24 on 2024-03-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_auto_20240302_0827"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sku",
            old_name="price",
            new_name="selling_price",
        ),
        migrations.AddField(
            model_name="sku",
            name="cost_price",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Cost price (Rs.)", verbose_name="Cost price (Rs.)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sku",
            name="platform_commission",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Commission for platform (Rs.)",
                verbose_name="Platform commission (Rs.)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sku",
            name="size",
            field=models.PositiveSmallIntegerField(
                help_text="Size of SKU in grams", verbose_name="Size (in grams)"
            ),
        ),
    ]
