# Generated by Django 3.2.24 on 2024-03-03 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_auto_20240302_1155"),
    ]

    operations = [
        migrations.AddField(
            model_name="sku",
            name="measurement_unit",
            field=models.CharField(
                choices=[
                    ("gm", "Grams"),
                    ("kg", "Kilograms"),
                    ("mL", "Milliliters"),
                    ("L", "Liters"),
                    ("pc", "Piece"),
                ],
                default="gm",
                max_length=2,
                verbose_name="Measurement Unit",
            ),
        ),
        migrations.AddField(
            model_name="sku",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Pending for approval"),
                    (1, "Approved"),
                    (2, "Discontinued"),
                ],
                default=0,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="sku",
            name="size",
            field=models.PositiveSmallIntegerField(
                help_text="Size of SKU in grams",
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="Size (in grams)",
            ),
        ),
    ]
