# Generated by Django 3.2.24 on 2024-03-03 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_auto_20240303_0430"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sku",
            name="size",
            field=models.PositiveSmallIntegerField(
                help_text="Size of SKU in defined unit",
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="Size (in defined unit)",
            ),
        ),
    ]
